export const DEFAULT_USD_RATE = 6.85;
export const DEFAULT_CLEARANCE_PROFIT_USD = 100;
export const DEFAULT_DELIVERY_PROFIT_USD = 100;
export const DEFAULT_CLEARANCE_DELIVERY_PROFIT_CNY = 685;
export const PERSONAL_CUSTOMER_COMMISSION_RATE = 0.15;
export const COMPANY_CUSTOMER_COMMISSION_RATE = 0.10;
export const HIGH_RISK_PROFIT_RATE_THRESHOLD = 0.10;
export const HIGH_PROFIT_RATE_THRESHOLD = 0.50;
